name: daily-report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # 8 AM ET

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main  # ✅ Ensure it's working directly on main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run automated pipeline
        run: python automated_pipeline.py

      - name: Commit and push CSV if not empty
        run: |
          FILE=$(ls pre_xynth_trades_*.csv | head -n 1)
          if [ -s "$FILE" ]; then
            echo "✅ $FILE is not empty. Committing to main..."
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add "$FILE"
            git commit -m "Add daily report: $FILE"
            git push origin HEAD:main
          else
            echo "⚠️ $FILE is empty. Skipping commit."
          fi
