name: daily-report

on:
  schedule:
    - cron: "0 12 * * *"  # runs daily at 8 AM ET (12:00 UTC)
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with push access
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run automated market pipeline
        run: |
          echo "🚀 Running automated pipeline..."
          python automated_pipeline.py

      - name: Commit and push output file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.csv
          git commit -m "Add daily report CSV $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
