name: Run Daily Market Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # 8 AM ET
    - cron: '0 */4 * * *'  # Every 4 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run automated market pipeline
        run: python automated_pipeline.py

      - name: Commit and Push CSV Report
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.csv
          git commit -m "Add daily report CSV"
          git push origin main
