name: daily-report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # 8 AM UTC

jobs:
  run-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <-- 🔑 Gives push access to GitHub Actions

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run automated market pipeline
        run: |
          echo "🚀 Running automated pipeline..."
          python automated_pipeline.py

      - name: Commit and push output CSV
        run: |
          FILE=$(ls pre_xynth_trades_*.csv | sort | tail -n 1)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git commit -m "Add daily report: $FILE" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
